"""
Django settings for IATI Account Web App project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os.path
import secrets
from pathlib import Path

import environ
import pytz
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from iati_account_web.helpers import _codelist_helper

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Setup environment variables.
env = environ.Env(
    DEBUG=(bool, False),
    SECRET_KEY=(str, secrets.token_urlsafe(50)),
    OIDC_OP_AUTHORIZATION_ENDPOINT=(str, "https://api.eu.asgardeo.io/t/iati/oauth2/authorize"),
    OIDC_OP_TOKEN_ENDPOINT=(str, "https://api.eu.asgardeo.io/t/iati/oauth2/token"),
    OIDC_OP_USER_ENDPOINT=(str, "https://api.eu.asgardeo.io/t/iati/oauth2/userinfo"),
    OIDC_OP_JWKS_ENDPOINT=(str, "https://api.eu.asgardeo.io/t/iati/oauth2/jwks"),
    OIDC_RP_CLIENT_ID=(str, None),
    OIDC_RP_CLIENT_SECRET=(str, None),
    SERVER_URL_BASE=(str, None),
    IDENTITY_SERVICE_BASE_URL=(str, None),
    IDENTITY_SERVICE_CLIENT_ID=(str, None),
    IDENTITY_SERVICE_CLIENT_SECRET=(str, None),
    IDENTITY_SERVICE_ROLE_ID_IATI_REGISTER_YOUR_DATA=(str, None),
    CRM_BASE_URL=(str, None),
    CRM_CLIENT_ID=(str, None),
    CRM_CLIENT_SECRET=(str, None),
    COUNTRY_CODELIST_JSON=(str, None),
    ORGANISATION_TYPE_CODELIST_JSON=(str, None),
    REGION_CODELIST_JSON=(str, None),
    LICENCE_JSON=(str, None),
    REGISTER_YOUR_DATA_BASE_URL=(str, None),
    STATIC_ROOT=(str, None),
    POSTGRES_NAME=(str, None),
    POSTGRES_USER=(str, None),
    POSTGRES_PASSWORD=(str, None),
    POSTGRES_HOST=(str, None),
    POSTGRES_PORT=(str, None),
    ALLOWED_HOSTS=(list, []),
)

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# SECURITY WARNING: don't run with debug turned on in production!
SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")

# Setup logging.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "WARNING",
    },
    "loggers": {
        "mozilla_django_oidc": {"handlers": ["console"], "level": "WARNING"},
        "django": {"handlers": ["console"], "level": "INFO"},
        "iati_account": {"handlers": ["console"], "level": "DEBUG"},
        "audit": {"handlers": ["console"], "level": "INFO"},
        "requests": {"handlers": ["console"], "level": "WARNING"},
        "requests_oauthlib": {"handlers": ["console"], "level": "WARNING"},
    },
}

# OIDC settings for communicating with the identity server.
OIDC_OP_AUTHORIZATION_ENDPOINT = env("OIDC_OP_AUTHORIZATION_ENDPOINT")
OIDC_OP_TOKEN_ENDPOINT = env("OIDC_OP_TOKEN_ENDPOINT")
OIDC_OP_USER_ENDPOINT = env("OIDC_OP_USER_ENDPOINT")
OIDC_OP_JWKS_ENDPOINT = env("OIDC_OP_JWKS_ENDPOINT")
OIDC_RP_CLIENT_ID = env("OIDC_RP_CLIENT_ID")
OIDC_RP_CLIENT_SECRET = env("OIDC_RP_CLIENT_SECRET")
OIDC_USERNAME_ALGO = "iati_account_web.oidc.generate_username"
OIDC_STORE_ACCESS_TOKEN = True
OIDC_STORE_ID_TOKEN = True
OIDC_CREATE_USER = True
OIDC_RP_SCOPES = (
    "openid email iati_account profile roles ryd "
    "ryd:reporting_org ryd:reporting_org:create ryd:reporting_org:update ryd:reporting_org:delete "
    "ryd:dataset ryd:dataset:update ryd:dataset:delete "
    "ryd:reporting_org:user ryd:reporting_org:user:update"
)
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_VERIFY_SSL = True
LOGIN_REDIRECT_URL = reverse_lazy("post-login")
LOGOUT_REDIRECT_URL = "/"
OIDC_OP_LOGOUT_URL_METHOD = "iati_account_web.oidc.logout_uri"
AUTHENTICATION_BACKENDS = ("iati_account_web.oidc.IATIAccountOIDCAuthBackend",)

SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

ALLOWED_HOSTS: list[str] = env("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "iati_account_web.welcome.apps.WelcomeConfig",
    "iati_account_web.account.apps.AccountConfig",
    "iati_account_web.data.apps.DataConfig",
    "django.contrib.auth",
    "django.contrib.admin",
    "mozilla_django_oidc",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "iati_account_web.exceptions_middleware.IATIAccountExceptionHandlerMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "mozilla_django_oidc.middleware.SessionRefresh",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "iati_account_web.urls"

MESSAGE_STORAGE = "django.contrib.messages.storage.fallback.FallbackStorage"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "iati_account_web/templates/"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "iati_account_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if env("POSTGRES_NAME"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("POSTGRES_NAME"),
            "USER": env("POSTGRES_USER"),
            "PASSWORD": env("POSTGRES_PASSWORD"),
            "HOST": env("POSTGRES_HOST"),
            "PORT": env("POSTGRES_PORT"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "account.IATIUser"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    #    ("fr", _("French")),
    ("en", _("English")),
]

LOCALE_PATHS = (BASE_DIR / "iati_account_web" / "locale",)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "iati_account_web" / "static",
]
if env("STATIC_ROOT"):
    STATIC_ROOT = env("STATIC_ROOT")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# These are the SCIM2 scopes that we use when making internal calls
# to the identity service.
IDENTITY_SERVICE_SCIM2_SCOPES = " ".join(
    [
        "internal_user_mgt_create",
        "internal_user_mgt_update",
        "internal_user_mgt_view",
        "internal_role_mgt_users_update",
    ]
)

# Format codelists into lists and lookups.
# NOTE: for the moment, this does not worry about the activity state of
# the codelist entry.
COUNTRY_LIST, COUNTRY_CODE_LOOKUP = _codelist_helper(env("COUNTRY_CODELIST_JSON"))
ORGANISATION_TYPE_LIST, ORGANISATION_TYPE_LOOKUP = _codelist_helper(env("ORGANISATION_TYPE_CODELIST_JSON"))
REGION_LIST, REGION_LOOKUP = _codelist_helper(env("REGION_CODELIST_JSON"))
LICENCE_LIST, LICENCE_LOOKUP = _codelist_helper(env("LICENCE_JSON"))

# Format a list of timezones using the internal list in pytz.  These
# are used to allow end users to select their timezone.
TIMEZONE_LIST = [("", "--")]
for tz in pytz.common_timezones:
    tz_parts = tz.replace("_", " ").split("/")
    if len(tz_parts) == 1:
        TIMEZONE_LIST.append((tz, f"{tz}"))
    elif len(tz_parts) == 2:
        region, city = tz_parts[0], tz_parts[1]
        TIMEZONE_LIST.append((tz, f"{city} - {region}"))
    elif len(tz_parts) == 3:
        region, country, city = tz_parts[0], tz_parts[1], tz_parts[2]
        TIMEZONE_LIST.append((tz, f"{city} - {country}/{region}"))
    else:
        raise ValueError()

# Additional choice fields
REPORTING_SOURCE_TYPE_LIST = [("primary_source", "Primary Source"), ("secondary_source", "Secondary Source")]
REPORTING_SOURCE_TYPE_LOOKUP = {x[0]: x[1] for x in REPORTING_SOURCE_TYPE_LIST}
VISIBILITY_LIST = [("private", "Private"), ("public", "Public")]
VISIBILITY_LOOKUP = {x[0]: x[1] for x in VISIBILITY_LIST}
USER_ROLE_LIST = [
    ("admin", "Admin"),
    ("editor", "Editor"),
    ("contributor", "Contributor"),
    ("provider_admin", "Provider Admin"),
    ("contributor_pending", "Pending"),
]
USER_ROLE_LOOKUP = {x[0]: x[1] for x in USER_ROLE_LIST}
