# Generated by Django 5.2.4 on 2025-11-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iatiuser",
            name="registry_id",
            field=models.CharField(blank=True, default="", max_length=36),
        ),
    ]
