# Generated by Django 5.2.4 on 2025-11-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_iatiuser_registry_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="iatiuser",
            name="has_been_provisioned",
            field=models.BooleanField(default=False),
        ),
    ]
