# Generated by Django 5.2.4 on 2025-12-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_iatiuser_has_been_provisioned"),
    ]

    operations = [
        migrations.AddField(
            model_name="iatiuser",
            name="use_cases_using_data",
            field=models.BooleanField(default=False),
        ),
    ]
