# Generated by Django 5.2.4 on 2025-12-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_iatiuser_use_cases_using_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="iatiuser",
            name="is_iati_superadmin",
            field=models.BooleanField(default=False),
        ),
    ]
