# Generated by Django 5.2.4 on 2026-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_iatiuser_is_iati_superadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="iatiuser",
            name="use_cases_forum",
            field=models.BooleanField(default=False),
        ),
    ]
